name: 'Build'

on: [push, pull_request]

env:
  CI: true
  DOCKER_BUILD_TAG: build-${{ github.run_number }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    env:
      YARN_CACHE_FOLDER: .yarn-cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn --frozen-lockfile
      - run: yarn test:once --maxWorkers=2
      - run: docker build --tag wowanalyzer-server .
      - name: Push to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: .